### ISSUE TITLE
[Question] Use case?

### ISSUE THREAD

**Issue by aehlke** [birros/libmpv-build#8]
Sorry for the naive question, but how can this be used on iOS/macOS platforms? Is Iina the only Apple platform library for using libmpv or do you have other pointers? Thanks.

**Comment by birros** [comment]
As mentioned in the `README` (perhaps incorrectly), this repo provides iOS & macOS libmpv builds for [media_kit](https://github.com/alexmercerind/media_kit) only.

I understand this is confusing, due to the fact that the `media_kit` repo is not yet part of the `media_kit` organization, it is still present on the account of its creator @alexmercerind for now.

Knowing that the build of libmpv and its dependencies is very time-consuming and specific to `media_kit` (see the config), this repo is not intended to provide a generic build that can be used by other projects. Even if, a project using the libmpv OpenGL API can use it.

So if the config doesn't meet your needs, I invite you to fork this repo, I've made the build on local macOS as isomorphic as possible with GitHub CI, modulo some syntax complexity.

**Comment by aehlke** [comment]
Thanks for explaining. You helped me find the answer I need - I believe I can still use this as a SwiftUI-oriented dev, by embedding media_kit/flutter into a SwiftUI view. So I don't need to pursue a Swift-native libmpv.
